version: '3.8'

services:
  web:
    image: bug_manage_platform
    container_name: bug_manage_platform
    ports:
      - "8080:8080"
    volumes:
      - /root/bug_manage_platform/code:/app
      - static_volume:/app/static
      - uwsgi_log:/var/log/uwsgi
    environment:
      - MYSQL_HOST=mysql
      - MYSQL_PORT=3306
      - MYSQL_ROOT_PASSWORD=123456
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_PASSWORD=123456
    depends_on:
      - mysql
      - redis
    networks:
      - bug_manage_platform_network
    restart: always

  mysql:
    container_name: mysql
    image: bitnami/mysql:latest
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=123456
      - MYSQL_DATABASE="BugManagePlatform"
    volumes:
      - /root/bug_manage_platform/mysql:/bitnami/mysql/data
    networks:
      - bug_manage_platform_network
    restart: always

  redis:
    container_name: redis
    image: bitnami/redis:latest
    ports:
      - "6379:6379"
    environment:
      - REDIS_PASSWORD=123456
    volumes:
      - /root/bug_manage_platform/redis:/bitnami/redis/data
    networks:
      - bug_manage_platform_network
    restart: always

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - /root/bug_manage_platform/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - web
    networks:
      - bug_manage_platform_network
    restart: always

networks:
  bug_manage_platform_network:
    driver: bridge

volumes:
  static_volume:
  uwsgi_log: 